import type { Metadata } from "next";
import { Glass_Antiqua } from "next/font/google";
import "./globals.css";

const glass = Glass_Antiqua({ subsets: ["latin"], weight: '400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={glass.className}>{children}</body>
    </html>
  );
}
